name: adhoc terraform execute

on:
  issue_comment:
    types: [ created ]
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-tf-execute-context-when-plan-comment:
    if: ${{ github.event.issue.pull_request }} && ${{ github.event.comment.body == 'plan' }}
    runs-on: ubuntu-22.04
    env:
      LABELS: ${{ toJson(github.event.issue.labels) }}
    steps:
      - name: Create targets
        run: |
          target_labels=$(echo ${LABELS} | jq '.[].name' | jq 'select(. | startswith("target:"))' | jq -c -s '.')
          env_labels=$(echo ${LABELS} | jq '.[].name' | jq 'select(. | startswith("env:"))' | jq -c -s '.')
          targets=$(echo ${target_labels} | sed 's/target://g')
          envs=$(echo ${env_labels} | sed 's/env://g')
          echo "targets: ${targets}"
          echo "envs: ${envs}"
          
          echo "TARGETS=${targets}" >> $GITHUB_OUTPUT
          echo "envs=${envs}" >> $GITHUB_OUTPUT
          
