name: Download artifact

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: false
        default: ${{ github.repository }}
      workflow:
        description: "artifactをuploadしたworkflowファイル名"
        type: string
        required: true
      branch:
        description: "artifactをuploadしたworkflowを実行したbranch"
        type: string
      name:
        description: "artifact名"
        type: string
        required: true
      pr:
        description: "Pull Requestの番号"
        type: number
      path:
        description: "artifactを保存するpath"
        type: string
        required: true


jobs:
  download-artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Run script
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #          refs: https://github.com/dawidd6/action-download-artifact/blob/master/main.js
          script: |
            const fs = require('fs')
            const pathname = require('path')
            try {              
              const [owner, repo] = core.getInput("repo", { required: true }).split("/")
              const name = core.getInput("name")
              const workflow = core.getInput("workflow")
              const pr = core.getInput("pr")
              const branch = core.getInput("branch")
            
              core.info(`==> Repository: ${owner}/${repo}`)
              core.info(`==> Artifact name: ${name}`)
              core.info(`==> Local path: ${path}`)
              core.info(`==> Workflow name: ${workflow}`)
              core.info(`==> PR: ${pr}`)
            
              
            } catch (error) {
                core.setOutput("found_artifact", false)
                core.setOutput("error_message", error.message)
                core.setFailed(error.message)
            }
      - name: Unzip
        run: |
          ls 
